# Generated by Django 4.0.7 on 2022-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0002_analyse_rubber'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse_rubber',
            name='type',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
