# Generated by Django 4.0.7 on 2022-10-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0003_analyse_rubber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse_rubber',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
