# Generated by Django 4.0.7 on 2022-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0004_alter_analyse_rubber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse_rubber',
            name='send_analyse',
            field=models.BooleanField(default=False),
        ),
    ]
