# Generated by Django 4.0.7 on 2022-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0005_analyse_rubber_send_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse_rubber',
            name='rubber_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
