# Generated by Django 4.0.7 on 2022-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0006_analyse_rubber_rubber_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing_rubber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=200)),
                ('recycle', models.CharField(max_length=200)),
                ('compound', models.CharField(max_length=200)),
                ('chemical_formula', models.CharField(max_length=200)),
                ('polymer', models.CharField(max_length=200)),
                ('mixing', models.CharField(max_length=200)),
                ('made_from_type', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('send_analyse', models.BooleanField(default=False)),
                ('rubber_type', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
