# Generated by Django 4.0.7 on 2022-10-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0007_testing_rubber'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse_rubber',
            name='send_report',
            field=models.BooleanField(default=False),
        ),
    ]
