# Generated by Django 4.0.7 on 2022-10-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0008_analyse_rubber_send_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing_rubber',
            name='output',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
