# Generated by Django 4.0.7 on 2022-10-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0009_testing_rubber_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing_rubber',
            name='rubber_type',
        ),
        migrations.RemoveField(
            model_name='testing_rubber',
            name='send_analyse',
        ),
    ]
