# Generated by Django 4.0.7 on 2022-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0010_remove_testing_rubber_rubber_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing_rubber',
            name='matching',
            field=models.BooleanField(default=False),
        ),
    ]
