# Generated by Django 4.0.7 on 2022-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_unit', '0011_testing_rubber_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing_rubber',
            name='send_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testing_rubber',
            name='send_testing',
            field=models.BooleanField(default=False),
        ),
    ]
