# Generated by Django 4.0.7 on 2022-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='natural_rubber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex_method', models.CharField(max_length=200)),
                ('latex_char', models.CharField(max_length=200)),
                ('acid', models.CharField(max_length=200)),
                ('Time_taken', models.PositiveIntegerField()),
                ('polymer', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('type_of_trees', models.CharField(max_length=200)),
                ('type_of_plants', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='synthetic_rubber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('polymer_type', models.CharField(max_length=200)),
                ('mineral_type', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('gases', models.CharField(max_length=200)),
                ('storage_type', models.CharField(max_length=200)),
                ('chemical_type', models.CharField(max_length=200)),
                ('rubber_type', models.CharField(max_length=200)),
            ],
        ),
    ]
