# Generated by Django 4.0.7 on 2022-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_natural_rubber_synthetic_rubber'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthetic_rubber',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
