# Generated by Django 4.0.7 on 2022-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_synthetic_rubber_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='send_natural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='synthetic_rubber',
            name='send_synthetic',
            field=models.BooleanField(default=False),
        ),
    ]
