# Generated by Django 4.0.7 on 2022-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_natural_rubber_send_natural_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='natural_rubber',
            name='need_latex',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='natural_rubber',
            name='remaining',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='synthetic_rubber',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='synthetic_rubber',
            name='need_chemical',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='synthetic_rubber',
            name='remaining',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
