# Generated by Django 4.0.7 on 2022-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_natural_rubber_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natural_rubber',
            name='availability',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='natural_rubber',
            name='need_latex',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='natural_rubber',
            name='remaining',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
