# Generated by Django 4.0.7 on 2022-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_natural_rubber_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='check_remaining',
            field=models.BooleanField(default=False),
        ),
    ]
