# Generated by Django 4.0.7 on 2022-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_natural_rubber_check_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='fixing_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
