# Generated by Django 4.0.7 on 2022-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_natural_rubber_fixing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='send_fixing_date',
            field=models.BooleanField(default=False),
        ),
    ]
