# Generated by Django 4.0.7 on 2022-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_natural_rubber_natural_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
