# Generated by Django 4.0.7 on 2022-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_natural_rubber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural_rubber',
            name='give_vendor',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
