# Generated by Django 4.0.7 on 2022-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_natural_rubber_give_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natural_rubber',
            name='Time_taken',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
