# Generated by Django 4.0.7 on 2022-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_natural_rubber_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthetic_rubber',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
