# Generated by Django 4.0.7 on 2022-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_synthetic_rubber_syn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthetic_rubber',
            name='give_vendor_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
